<?php


/**
 * Implements hook_context_plugins().
 */
function context_omniture_context_plugins() {
  $plugins = array();
  $plugins['context_omniture_reaction'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_omniture') .'/plugins',
      'file' => 'context_omniture_reaction.inc',
      'class' => 'context_omniture_reaction',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_omniture_context_registry() {
  $reg = array(
    'reactions' => array(
      'context_omniture_reaction' => array(
        'title' => t('Omniture'),
        'plugin' => 'context_omniture_reaction',
      ),
    ),
  );
  return $reg;
}

/**
 * Implements hook_omniture_variables().
 */
function context_omniture_omniture_variables() {

  //get variables from context 
  if ($plugin = context_get_plugin('reaction', 'context_omniture_reaction')) {
    $variables = $plugin->execute($vars);
    dpm($variables);
    return array("variables" => $variables);
  } 
}
